- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: feature
  color: "a2eeef"
  description: "New feature or request"

- name: hr
  color: "5319e7"
  description: "Domínio de RH"

- name: chore
  color: "fef2c0"
  description: "Maintenance and housekeeping"

- name: docs
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: perf
  color: "f9d0c4"
  description: "Performance improvements"

- name: refactor
  color: "e4e669"
  description: "Code refactoring"

- name: test
  color: "bfe5bf"
  description: "Adding missing tests or correcting existing tests"

- name: ci
  color: "ff6600"
  description: "Continuous integration and deployment"

- name: security
  color: "ee0701"
  description: "Security related issues"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"